# Generated by Django 6.0.1 on 2026-02-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="content",
            field=models.FilePathField(
                blank=True, path="/home/", verbose_name="Текст книги"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="front_cover",
            field=models.FilePathField(
                blank=True, path="/", verbose_name="Обложка книги"
            ),
        ),
    ]
