# Generated by Django 6.0.1 on 2026-02-03 16:02

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_content_alter_book_front_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="content",
            field=models.FilePathField(
                blank=True,
                path=pathlib.PurePosixPath(
                    "/home/ilrosch/projects/django/books_shop/books/data/contents"
                ),
                verbose_name="Текст книги",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="front_cover",
            field=models.FilePathField(
                blank=True,
                path=pathlib.PurePosixPath(
                    "/home/ilrosch/projects/django/books_shop/books/data/images"
                ),
                verbose_name="Обложка книги",
            ),
        ),
    ]
