# Generated by Django 6.0.1 on 2026-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_content_alter_book_front_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="content",
            field=models.FileField(
                blank=True, upload_to="books/data/contents", verbose_name="Текст книги"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="front_cover",
            field=models.FileField(
                blank=True, upload_to="books/data/images", verbose_name="Обложка книги"
            ),
        ),
    ]
