# Generated by Django 6.0.1 on 2026-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_content_alter_book_front_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена"),
        ),
    ]
